name: Test Lambda Functions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install boto3
          pip install -r hello_world/requirements.txt || true
          pip install -r put_visitor/requirements.txt || true

      - name: Run Get Visitor tests
        run: |
          cd get_visitor
          python test_app.py
