name: Test and Deploy Lambda Functions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install boto3
          pip install -r hello_world/requirements.txt || true
          pip install -r put_visitor/requirements.txt || true

      - name: Run Get Visitor tests
        run: |
          cd get_visitor
          python test_app.py

      - name: Run Put Visitor tests
        run: |
          cd put_visitor
          python test_app.py

  deploy-infra:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Build with SAM
        run: sam build --template template.yaml
        working-directory: ./  # ✅ Fixes the incorrect path issue

      - name: Deploy with SAM
        run: sam deploy --template template.yaml --no-confirm-changeset --no-fail-on-empty-changeset --stack-name cloud-resume-challenge --capabilities CAPABILITY_IAM
        working-directory: ./  # ✅ Makes sure it runs from correct path
